services:
  eureka:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  booking-service:
    build: ./booking-service
    container_name: booking-service
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka/

  hotel-service:
    build: ./hotel-service
    container_name: hotel-service
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka/

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - eureka
      - booking-service
      - hotel-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka/

